### ISSUE TITLE
Use Godoc for documentation

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/libaudit-go#13]
http://godoc.org/golang.org/x/tools/cmd/godoc
https://godoc.org/

Good doc is quite important for a package/library. Currently the readme.md doc is nice, but doc-from-code is nicer and always more accurate. I would change the readme to only give the high level guidance and how to get started then point to godoc (it can be local, not necessarily on godoc.org, or in both places even) so that doc is always correct.

If using a makefile, a target to generate the doc would also be good, see issue #12 that is related

**Comment by arunk-s** [comment]
Fixed via https://github.com/mozilla/libaudit-go/commit/263c1554c5b936b455a1f313f9e0942e9d92dac0
