### ISSUE TITLE
Misc / review

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/libaudit-go#15]
- https://github.com/mozilla/libaudit-go/blob/master/audit_events.go#L107
- https://github.com/mozilla/libaudit-go/blob/master/audit_events.go#L47
- https://github.com/mozilla/libaudit-go/blob/master/audit_events.go#L77

(error handling) If err != 0 continue? the double statement seems not necessary
The follow-up "continue" might need to return error conditions to the caller though (instead of https://github.com/mozilla/libaudit-go/blob/master/audit_events.go#L51)

- https://github.com/mozilla/libaudit-go/blob/master/audit_x64_i2s.go
Not a huge problem but this should probably be done programmatically from https://github.com/mozilla/libaudit-go/blob/master/audit_x64.go / clearer/easier when new syscalls are added, etc.
See https://play.golang.org/p/mCFmRT8nzP for example. 

- https://github.com/mozilla/libaudit-go/blob/master/auditconstant_string.go
Short of doing the automation in go, would be good to have the command in the makefile as per issue #12 so one could just run "make depends" for example

- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L645
Line return ;-)

- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L747
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L914
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L975
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1011
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1058
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1093
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1137
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1194
- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1280
- etc...

- https://github.com/mozilla/libaudit-go/blob/master/interpret.go#L1670 
- https://github.com/mozilla/libaudit-go/blob/master/ruledata.go#L69
seems unused

The maps should probably be in a separate file for maintainability. Maybe put all this + syscall name in a separate directory such as "go-kernel-headers" so that it's clean-enough

**Comment by arunk-s** [comment]
Re: >https://github.com/mozilla/libaudit-go/blob/master/auditconstant_string.go
Short of doing the automation in go, would be good to have the command in the makefile as per issue #12 so one could just run "make depends" for example

Quoting the go blog on generate https://blog.golang.org/generate: 
>Also, if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients.

As the library will be made available via go get so shouldn't we include the generated file in the library code, it will also make sure that the client need not to run `make` before using the lib and can directly use it.
If ever the constants are updated, we'll run the generate again to update the string maps as well.

**Comment by arunk-s** [comment]
Fixed via https://github.com/mozilla/libaudit-go/commit/ad0e284a738b7a1a5326af155eb2196a7c900e5d and https://github.com/mozilla/libaudit-go/commit/d91e9d528b552fda7e66b011115e11e166e08083
