### ISSUE TITLE
Libaudit test uses auditctl for verifying test results

### ISSUE THREAD

**Issue by arunk-s** [mozilla/libaudit-go#16]
Currently `libaudit_tests.go` uses ouput of `auditctl` command to check if `libaudit` functions worked correctly. This behaviour should be changed so that we don't rely on `auditctl` and our tests should not break if `auditctl` changes its output behaviour or even `auditctl` is absent on the client's machine.

**Comment by ameihm0912** [comment]
Leaning towards just closing this, feel free to reopen if anyone disagrees; using auditctl in the test seems like a nice way to externally validate the rule setter functions are working as expected, and also confirm our rule list output matches what we expect. I think, so long as the rules list is outputting rules in auditctl compatible format we should keep this validation.
