### ISSUE TITLE
Do not panic on rule load failure

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/libaudit-go#18]
Eg:

> panic: SetRules failed: auditSetupAndAddWatchDir failed: file at /etc/systemd does not exist

Instead this should be a warning. The reason for that is the same reason audit does not necessarily fails (depending on settings). It allows for ensuring the daemon starts even if your configuration differs.

It would also be ok to make the skip optional

**Comment by arunk-s** [comment]
Currently the strict path checking has been made optional by https://github.com/mozilla/libaudit-go/commit/2aec40d026c87451dbc7d14357c59567cd26cc92 .
Ideally the behaviour is to return an error type denoting warning (many such warnings can have the same type) and the client can then decide based on the type to either ignore or take appropriate action. For eg. MIG module can simply print the warning on stdout.
