### ISSUE TITLE
The data of NetlinkMessage message is truncated

### ISSUE THREAD

**Issue by rexrock** [mozilla/libaudit-go#24]
I'm not sure whether it's kernel's BUG or libaudit-go's BUG。

The following is the definition of nlmsghdr, nlmsg_len is the length of message including header
```
struct nlmsghdr {
    __u32       nlmsg_len;  /* Length of message including header */                                                                                          
    ......                                                                                                  
};
```

But in kernel, the nlmsg_len is the length of message, excluding header
```
struct sk_buff *audit_make_reply(__u32 portid, int seq, int type, int done,
				 int multi, const void *payload, int size)
{
    ......
    nlh	= nlmsg_put(skb, portid, seq, t, size, flags);
    ......
}
```

So, if we do as the following steps in libaudit-go, the data of NetlinkMessage message will be truncated
```
func parseAuditNetlinkMessage(b []byte) (ret []NetlinkMessage, err error) {                                                                                   
    ......
    datalen := m.Header.Len - syscall.NLMSG_HDRLEN 
    ......
}
```

In fact I think it's the BUG of kernel,

**Comment by ameihm0912** [comment]
@rexrock thanks for this, I think we may be OK here...

`nlmsg_put` actually ends up calling `__nlmsg_put`

https://github.com/torvalds/linux/blob/master/include/net/netlink.h#L466-L473

`__nlmsg_put` calculates a size based on the supplied payload length

https://github.com/torvalds/linux/blob/master/net/netlink/af_netlink.c#L2105

This looks like it makes the required adjustment to the header length value to include the header size.

https://github.com/torvalds/linux/blob/master/include/net/netlink.h#L280-L283

**Comment by ameihm0912** [comment]
Reopening this, I have observed this behavior with certain message types (it appears to be dependent on where the event comes from, some pieces of the audit kernel code use the netlink headers and others are manually setting length values e.g., https://github.com/torvalds/linux/blob/master/kernel/audit.c#L2302

I'm not sure if the netlink payload length can be reliably used
