### ISSUE TITLE
Please make it compatible with FreeBSD

### ISSUE THREAD

**Issue by yurivict** [mozilla/libaudit-go#36]
For example, FreeBSD doesn't have Netlink:
https://github.com/mozilla/libaudit-go/blob/master/libaudit.go#L38

**Comment by ameihm0912** [comment]
@yurivict thanks for the note on this

Yeah this would be a nice feature -- our intent was focused on Linux audit, but this could probably be adapted to BSD by adding support for parsing BSM audit records via auditpipe and thinking about a nice normalization method
