### ISSUE TITLE
Replace log package for warnings/errors to be redirected to stderr

### ISSUE THREAD

**Issue by arunk-s** [mozilla/libaudit-go#4]
We are using `log` package for notifying of both logs and errors which is not desirable.
A suitable package/way should exist to separate them and direct them to `stdout` or `stderr`

As suggested by @hardikj :
> Also for string like "Acknowledged!!" and "NLMSG ERROR", I would recommend to implement a 
> debug flag and print them in debug flag only.

**Comment by gdestuynder** [comment]
I suspect we should not do that since its a library, its not expected to use stdout/err for passing warnings, msgs, etc over.
I'd say use the log package for normal log messages (info, warning, etc) and pass errors directly via function return to the underlying program/user of the go package.

**Comment by arunk-s** [comment]
I've update the current code to remove any logging and now we are directing any warnings as error messages to the caller. There are only a few instances of warnings though.

**Comment by gdestuynder** [comment]
once you're confident its the case everywhere can just close the issue :) (bonus points if you refer to the commits that fix it)

**Comment by arunk-s** [comment]
Fixed via https://github.com/mozilla/libaudit-go/commit/0a45716ac1ebe07c2624f2684c71b4895241c752
