### ISSUE TITLE
FileWatch Output is Null

### ISSUE THREAD

**Issue by shinetots** [mozilla/libaudit-go#9]
I have this rule:  -w /home/sunshine/Documents/files -p rwxa -k file . 
When I ran "sudo go run main.go audit.rules", audit events were shown except for file watches. I always get this output. Type:EOF Info: {}. The info is always null.

**Comment by arunk-s** [comment]
I've tried to verify that the file watches works correctly and on my system, the watch is working successfully.
On the message type, I think what you are getting is:
```bash
Type:EOE Info: {}
```
rather than `EOF` because only `AUDIT_EOE` event type is available (no AUDIT_EOF) in audit framework.
We deal with type parsing in libaudit-go [here](https://github.com/mozilla/libaudit-go/blob/master/audit_events.go#L86) and in `main.go` the message is packed [here](https://github.com/mozilla/audit-go/blob/master/main.go#L38).
I will recommend to you to run `sudo auditctl -l` to see if the rule is applied correctly as you've mentioned.
Then try to change some content in the file or directory you specified and see if the `audit-go` emit some events.

**Comment by shinetots** [comment]
Ah yes, it's EOE. When I ran sudo auditctl -l, I did not see the filewatch rule I added.

**Comment by arunk-s** [comment]
Oh, It shouldn't happen that way. Can you try the same rules by putting them in `/etc/audit/audit.rules` and see if `auditd` detects them ? You can check the same by `auditctl -l`.
Also try to add just your `-w /home...` rule by adding only a single rule in a new file and pointing `main.go` to the same.
It should be some error at the configuration level.

**Comment by shinetots** [comment]
I have already made some changes in the configuration, and adding rules again, they're already shown after I ran auditctl -l. I tested with only 1 permission(r/read), then aafter I open a file, so many event were recorded. Is this how should it be?

2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"2ac6f1b","a1":"2d6b5f0","a2":"2aa8410","a3":"58c","arch":"c000003e","auid":"4294967295","comm":"nautilus","egid":"0","euid":"0","exe":"/usr/bin/nautilus","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5013","ppid":"1582","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"nautilus"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"2ac6f1c","a1":"2d6b5f0","a2":"2aa8410","a3":"58c","arch":"c000003e","auid":"4294967295","comm":"nautilus","egid":"0","euid":"0","exe":"/usr/bin/nautilus","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5013","ppid":"1582","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"nautilus"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"2ac6f21","a1":"2d6b5f0","a2":"2aa8410","a3":"58c","arch":"c000003e","auid":"4294967295","comm":"nautilus","egid":"0","euid":"0","exe":"/usr/bin/nautilus","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5013","ppid":"1582","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Details:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
info:{"proctitle":"nautilus"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"2ac6f22","a1":"2d6b5f0","a2":"2aa8410","a3":"58c","arch":"c000003e","auid":"4294967295","comm":"gedit","egid":"0","euid":"0","exe":"/usr/bin/gedit","exit":"0","fsgid":"0","fsuid":"0","gid":"0","items":"2","key":"exec","pid":"5013","ppid":"1582","ses":"4294967295","sgid":"0","success":"yes","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:EXECVE		
Info:{"a0":"gedit","a1":"/home/sunshine/jxtn/LICENSE","argc":"2"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"dev":"08:11","inode":"9437591","item":"0","mode":"0100755","nametype":"NORMAL","ogid":"0","ouid":"0","rdev":"00:00"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"dev":"08:11","inode":"12851381","item":"1","mode":"0100755","nametype":"NORMAL","ogid":"0","ouid":"0","rdev":"00:00"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"nautilus"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"19781cb","a1":"1978210","a2":"19422e0","a3":"96","arch":"c000003e","auid":"4294967295","comm":"gedit","egid":"0","euid":"0","exe":"/usr/bin/gedit","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5015","ppid":"5013","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"6765646974002F686F6D652F73756E7368696E652F6A78746E2F4C4943454E5345"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"19781cc","a1":"1978210","a2":"19422e0","a3":"96","arch":"c000003e","auid":"4294967295","comm":"gedit","egid":"0","euid":"0","exe":"/usr/bin/gedit","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5015","ppid":"5013","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"6765646974002F686F6D652F73756E7368696E652F6A78746E2F4C4943454E5345"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"19781d1","a1":"1978210","a2":"19422e0","a3":"96","arch":"c000003e","auid":"4294967295","comm":"gedit","egid":"0","euid":"0","exe":"/usr/bin/gedit","exit":"-2","fsgid":"0","fsuid":"0","gid":"0","items":"1","key":"exec","pid":"5015","ppid":"5013","ses":"4294967295","sgid":"0","success":"no","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"item":"0","nametype":"UNKNOWN"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"6765646974002F686F6D652F73756E7368696E652F6A78746E2F4C4943454E5345"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}


2016/04/18 08:47:15 
Type:SYSCALL		
Info:{"a0":"19781d2","a1":"1978210","a2":"19422e0","a3":"96","arch":"c000003e","auid":"4294967295","comm":"dbus-launch","egid":"0","euid":"0","exe":"/usr/bin/dbus-launch","exit":"0","fsgid":"0","fsuid":"0","gid":"0","items":"2","key":"exec","pid":"5015","ppid":"5013","ses":"4294967295","sgid":"0","success":"yes","suid":"0","syscall":"59","tty":"pts18","uid":"0"}


2016/04/18 08:47:15 
Type:EXECVE		
Info:{"a0":"dbus-launch","a1":"--autolaunch=90bfc237040e43eb9ff94313adcbb134","a2":"--binary-syntax","a3":"--close-stderr","argc":"4"}


2016/04/18 08:47:15 
Type:CWD		
Info:{"cwd":"/home/sunshine"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"dev":"08:11","inode":"9437377","item":"0","mode":"0100755","nametype":"NORMAL","ogid":"0","ouid":"0","rdev":"00:00"}


2016/04/18 08:47:15 
Type:PATH		
Info:{"dev":"08:11","inode":"12851381","item":"1","mode":"0100755","nametype":"NORMAL","ogid":"0","ouid":"0","rdev":"00:00"}


2016/04/18 08:47:15 
Type:PROCTITLE		
Info:{"proctitle":"6765646974002F686F6D652F73756E7368696E652F6A78746E2F4C4943454E5345"}


2016/04/18 08:47:15 
Type:EOE		
Info:{}

**Comment by arunk-s** [comment]
You can delete the previously added rules by `sudo auditctl -D`. I'll suggest to create a new rule file, you can name it differently and only add the new rule to it. As you saw, after adding the read-only rule you are getting appropriate events in `audit-go`.
I'll suggest to direct `audit-go` to the new rules file : `sudo go run main.go new-rules-file`, then
do `auditctl -l` to see if rule are loaded correctly. If they are, then you should see events emitting from `audit-go` program.
As I said earlier the error seems to be in configuration somewhere.

**Comment by shinetots** [comment]
Ok great! Thanks! Anyways, I added another rule "-a always, exit -F dir=/files/ -p rwa -k file-access". After I ran the program, this error came out. "Setting Rule Unsuccessful:  Filter can only be used with AUDIT_EXIT" . What do you mean by this?

**Comment by arunk-s** [comment]
Your rule syntax is incorrect. `-a always, exit -F dir=/files/ -p rwa -k file-access` should be
`-a always, exit -w=/files/ -p rwa -k file-access`. That's why `audit-go` is showing error for rule setting.
`-F` flag in your case is empty, which is not allowed.
If you want to edit the way audit events are displayed, `AuditRuleFieldPairData` is not the function you want to edit. That function is used to set appropriate rules in audit framework.
I suggest editing `audit_events.go` for that purpose. The `netlinkAudit.AuditEvent` structure holds the info coming from kernel. You can start with editing `EventCallback` in main.go and start upwards from there. `ruledata.go` is mainly for the purpose of setting and deleting rules.

**Comment by shinetots** [comment]
Thanks. I got it. For the audit events(particularly for the Data), I only want the path, nametype, comm, exe and syscall to be displayed. Is it possible?

**Comment by arunk-s** [comment]
Yes, that is possible. But the fields like path, syscall, exec are available only on certain audit-event types (see audit logs to get more examples). So you'll have to add code to check for appropriate audit-event type and then split the data into fields, and only emit those that you want. You can start with editing `EventCallback` in main.go.

**Comment by shinetots** [comment]
And how about for translating those hexadecimal-format log messages into words readable by human?

**Comment by arunk-s** [comment]
The recommended way to decode them is via `ausearch -i` utility. (source https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security_Guide/sec-Understanding_Audit_Log_Files.html)
I suggest you to look for inspiration in the source code of [`ausearch`](https://fedorahosted.org/audit/browser/trunk/src).

**Comment by shinetots** [comment]
Yes, I have tried ausearch already  and even aureport in getting summary of decoded events. What I'm trying to do is for every event that will pop up while running the program, the data are already decoded of readable by humans. Thanks for the advice !

**Comment by arunk-s** [comment]
Sure. No problem. :)
